-- Nöggi-Kahoot → dm-quiz project: step 1 of 2, the EXPORT (18.09.2026)
--
-- Why: the Supabase free plan allows two active projects. The wedding quiz moves
-- into the dm-quiz project (bvglvdcndhqrvpnghrkp) so this one can be paused.
--
-- Run this in the OLD project's SQL editor (opgbezlecbggnqzlvhja). It reads and
-- changes nothing. The result is one cell, «import_script»: copy that whole cell
-- and run it in the dm-quiz project's SQL editor (step 2). The script creates the
-- schema «noeggi» there (the quiz's own schema; the DM app's tables are never touched),
-- copies every row, and ends with a ✅/❌ table: row counts and checksums of every
-- table must match what this export counted.
--
-- The script carries the guests' data (names, tokens), so it never goes into the
-- repo or a chat: straight from one SQL editor into the other.

with
sc as (
  select count(*) n,
    coalesce(string_agg(format('(%s,%L,%s,%s,%s,%L,%L)', id, name, score, correct, len, mode, created_at),
      E',\n' order by id), '') v,
    md5(coalesce(string_agg(format('%L|%L|%L|%L|%L|%L|%L', id, name, score, correct, len, mode, created_at),
      E'\n' order by id), '')) h
  from public.scores),
pl as (
  select count(*) n,
    coalesce(string_agg(format('(%L,%L,%L,%L,%L)', token, name, collected, fp, updated_at),
      E',\n' order by token), '') v,
    md5(coalesce(string_agg(format('%L|%L|%L|%L|%L', token, name, collected, fp, updated_at),
      E'\n' order by token), '')) h
  from public.players),
fb as (
  select count(*) n,
    coalesce(string_agg(format('(%s,%L,%L,%L,%L,%L,%L)', id, qid, claim, name, token, lang, created_at),
      E',\n' order by id), '') v,
    md5(coalesce(string_agg(format('%L|%L|%L|%L|%L|%L|%L', id, qid, claim, name, token, lang, created_at),
      E'\n' order by id), '')) h
  from public.feedback),
bo as (
  select count(*) n,
    coalesce(string_agg(format('(%s,%L,%s,%L,%L)', id, name, points, reason, created_at),
      E',\n' order by id), '') v,
    md5(coalesce(string_agg(format('%L|%L|%L|%L|%L', id, name, points, reason, created_at),
      E'\n' order by id), '')) h
  from public.bonus)
select
$IMPORT$-- Nöggi-Kahoot → dm-quiz project: step 2 of 2, the IMPORT
-- Generated by docs/move-to-dm-quiz-export.sql in the old project. Run it in the
-- dm-quiz project's SQL editor. Safe to run again (existing rows are kept).
--
-- One project, two apps, never mixed: everything of the wedding quiz lives in the
-- schema «noeggi» (same table and function names as before), DM stays in «public».
-- Only anon gets rights here, and only the ones the quiz uses; nothing in this
-- script reads or changes anything outside «noeggi». The quiz uses no Auth and no
-- Storage.
-- The API must expose the schema (Project Settings → API → Exposed schemas: add
-- noeggi), or the quiz gets «Invalid schema: noeggi».

create schema if not exists noeggi;
revoke all on schema noeggi from public;
grant usage on schema noeggi to anon;

-- ------------------------------------------------------------------ tables
create table if not exists noeggi.scores (
  id bigint generated always as identity primary key,
  name text not null check (char_length(name) between 1 and 14),
  score int not null check (score between 0 and 40000),
  correct int not null check (correct between 0 and 23),
  len int not null check (len in (10,23)),
  mode text not null check (mode in ('23','10','⚡10','👾10')),
  created_at timestamptz not null default now()
);
create table if not exists noeggi.players (
  token uuid primary key,
  name text not null check (char_length(name) between 1 and 14),
  collected jsonb not null default '[]',
  fp text,
  updated_at timestamptz not null default now()
);
create index if not exists players_fp_idx on noeggi.players (fp);
create table if not exists noeggi.feedback (
  id bigint generated always as identity primary key,
  qid text not null check (char_length(qid) between 1 and 40),
  claim text not null check (char_length(claim) between 1 and 200),
  name text check (char_length(name) between 1 and 14),
  token uuid,
  lang text check (lang in ('de','fr','en')),
  created_at timestamptz not null default now()
);
create table if not exists noeggi.bonus (
  id bigint generated always as identity primary key,
  name text not null check (char_length(name) between 1 and 14),
  points int not null check (points between -40000 and 40000),
  reason text,
  created_at timestamptz not null default now()
);

-- ------------------------------------------ access: the same as in the old project
-- scores: anon inserts and reads (the leaderboard). players: no direct access,
-- only through the functions below. feedback: anon inserts only. bonus: anon reads.
-- Table rights are granted explicitly (and nothing else), RLS on top as before.
revoke all on all tables in schema noeggi from public, anon, authenticated;
grant select, insert on noeggi.scores   to anon;
grant insert         on noeggi.feedback to anon;
grant select         on noeggi.bonus    to anon;
alter table noeggi.scores   enable row level security;
alter table noeggi.players  enable row level security;
alter table noeggi.feedback enable row level security;
alter table noeggi.bonus    enable row level security;
drop policy if exists "anon insert" on noeggi.scores;
drop policy if exists "anon read"   on noeggi.scores;
drop policy if exists "anon insert" on noeggi.feedback;
drop policy if exists "anon read"   on noeggi.bonus;
create policy "anon insert" on noeggi.scores   for insert to anon with check (true);
create policy "anon read"   on noeggi.scores   for select to anon using (true);
create policy "anon insert" on noeggi.feedback for insert to anon with check (true);
create policy "anon read"   on noeggi.bonus    for select to anon using (true);

create or replace function noeggi.player_get(tok uuid)
returns table(name text, collected jsonb)
language sql security definer set search_path = noeggi as
$$ select name, collected from noeggi.players where token = tok $$;

create or replace function noeggi.player_upsert(tok uuid, pname text, pcollected jsonb, pfp text)
returns void language sql security definer set search_path = noeggi as
$$ insert into noeggi.players(token, name, collected, fp) values (tok, pname, pcollected, pfp)
   on conflict (token) do update set name = excluded.name,
     collected = excluded.collected, fp = excluded.fp, updated_at = now() $$;

create or replace function noeggi.player_by_fp(pfp text)
returns table(token uuid, name text, collected jsonb)
language sql security definer set search_path = noeggi as
$$ select token, name, collected from noeggi.players
   where fp = pfp and length(coalesce(pfp,'')) > 8
     and (select count(*) from noeggi.players p2 where p2.fp = pfp) = 1 $$;

create or replace function noeggi.player_by_name(pname text)
returns table(token uuid, name text, collected jsonb)
language sql security definer set search_path = noeggi as
$$ select token, name, collected from noeggi.players
   where lower(name) = lower(pname)
     and (select count(*) from noeggi.players p2 where lower(p2.name) = lower(pname)) = 1 $$;

create or replace function noeggi.feedback_list()
returns table(created_at timestamptz, qid text, claim text, name text, lang text)
language sql security definer set search_path = noeggi as
$$ select f.created_at, f.qid, f.claim, f.name, f.lang
   from noeggi.feedback f order by f.created_at desc limit 200 $$;

revoke all on all functions in schema noeggi from public, anon, authenticated;
grant execute on function noeggi.player_get(uuid) to anon;
grant execute on function noeggi.player_upsert(uuid, text, jsonb, text) to anon;
grant execute on function noeggi.player_by_fp(text) to anon;
grant execute on function noeggi.player_by_name(text) to anon;
grant execute on function noeggi.feedback_list() to anon;

-- -------------------------------------------------------------------- data
$IMPORT$
|| case when sc.n = 0 then '' else
   'insert into noeggi.scores (id, name, score, correct, len, mode, created_at) overriding system value values'
   || E'\n' || sc.v || E'\non conflict (id) do nothing;\n' end
|| case when pl.n = 0 then '' else
   'insert into noeggi.players (token, name, collected, fp, updated_at) values'
   || E'\n' || pl.v || E'\non conflict (token) do nothing;\n' end
|| case when fb.n = 0 then '' else
   'insert into noeggi.feedback (id, qid, claim, name, token, lang, created_at) overriding system value values'
   || E'\n' || fb.v || E'\non conflict (id) do nothing;\n' end
|| case when bo.n = 0 then '' else
   'insert into noeggi.bonus (id, name, points, reason, created_at) overriding system value values'
   || E'\n' || bo.v || E'\non conflict (id) do nothing;\n' end
|| $IMPORT$
-- new rows continue after the copied ids
select setval(pg_get_serial_sequence('noeggi.scores', 'id'),   coalesce((select max(id) from noeggi.scores), 0) + 1, false);
select setval(pg_get_serial_sequence('noeggi.feedback', 'id'), coalesce((select max(id) from noeggi.feedback), 0) + 1, false);
select setval(pg_get_serial_sequence('noeggi.bonus', 'id'),    coalesce((select max(id) from noeggi.bonus), 0) + 1, false);

notify pgrst, 'reload schema';

-- ------------------------------------------------------------------ checks
create temp table if not exists _noeggi_check (n int, check_name text, ok boolean, detail text);
truncate _noeggi_check;
create temp table if not exists _noeggi_expected (t text, n bigint, h text);
truncate _noeggi_expected;
insert into _noeggi_expected values
$IMPORT$
|| format('  (%L, %s, %L), (%L, %s, %L), (%L, %s, %L), (%L, %s, %L);',
     'scores', sc.n, sc.h, 'players', pl.n, pl.h, 'feedback', fb.n, fb.h, 'bonus', bo.n, bo.h)
|| $IMPORT$

do $$
declare e record; got bigint; h text; v int; w int; x int; y int; i int := 0;
begin
  for e in select * from _noeggi_expected order by t loop
    i := i + 1;
    execute format('select count(*) from noeggi.%I', e.t) into got;
    if e.t = 'scores' then
      select md5(coalesce(string_agg(format('%L|%L|%L|%L|%L|%L|%L', id, name, score, correct, len, mode, created_at), E'\n' order by id), '')) into h from noeggi.scores;
    elsif e.t = 'players' then
      select md5(coalesce(string_agg(format('%L|%L|%L|%L|%L', token, name, collected, fp, updated_at), E'\n' order by token), '')) into h from noeggi.players;
    elsif e.t = 'feedback' then
      select md5(coalesce(string_agg(format('%L|%L|%L|%L|%L|%L|%L', id, qid, claim, name, token, lang, created_at), E'\n' order by id), '')) into h from noeggi.feedback;
    else
      select md5(coalesce(string_agg(format('%L|%L|%L|%L|%L', id, name, points, reason, created_at), E'\n' order by id), '')) into h from noeggi.bonus;
    end if;
    insert into _noeggi_check values (i, e.t || ': all rows copied', got = e.n and h = e.h,
      got || ' of ' || e.n || ' rows' || case when h = e.h then ', checksum matches' else ', CHECKSUM DIFFERS' end);
  end loop;

  -- the wedding quiz, as its guests (anon), sees exactly what it saw before
  perform set_config('request.jwt.claims', '{"role":"anon"}', true);
  set local role anon;
  select count(*) into v from noeggi.scores;
  select count(*) into x from noeggi.bonus;
  select count(*) into y from noeggi.feedback_list();
  reset role;
  insert into _noeggi_check values
    (5, 'Guests read the leaderboard and bonus', v = (select count(*) from noeggi.scores) and x = (select count(*) from noeggi.bonus),
        v || ' scores, ' || x || ' bonus rows'),
    (6, 'Guests cannot read players directly (only via the functions)',
        not has_table_privilege('anon', 'noeggi.players', 'select'), 'no select right on noeggi.players'),
    (7, 'Report list works', y = least((select count(*) from noeggi.feedback), 200), y || ' reports');

  -- logged-in users (DM accounts share this project's Auth) get nothing in this schema
  insert into _noeggi_check values (8, 'Only anon has rights in schema noeggi',
    not has_schema_privilege('authenticated', 'noeggi', 'usage')
    and not exists (select 1 from information_schema.role_table_grants
                    where table_schema = 'noeggi' and grantee not in ('anon', 'postgres', 'service_role', 'supabase_admin', current_user)),
    'authenticated: no usage of the schema; table rights only for anon (plus the admin roles)');
  perform set_config('request.jwt.claims', '', true);
end $$;

select case when ok then '✅' else '❌' end as " ", check_name, detail
  from _noeggi_check order by n;
$IMPORT$ as import_script
from sc, pl, fb, bo;
