-- Nöggi-Kahoot → dm-quiz project: step 1 of 2, the EXPORT (18.09.2026)
--
-- Why: the Supabase free plan allows two active projects. The wedding quiz moves
-- into the dm-quiz project (bvglvdcndhqrvpnghrkp) so this one can be paused.
--
-- Run this in the OLD project's SQL editor (opgbezlecbggnqzlvhja). It reads and
-- changes nothing. The result is one cell, «import_script»: copy that whole cell
-- and run it in the dm-quiz project's SQL editor (step 2). The script creates the
-- nk_* tables there (own names, next to DM's dm_* tables, which it never touches),
-- copies every row, and ends with a ✅/❌ table: row counts and checksums of every
-- table must match what this export counted.
--
-- The script carries the guests' data (names, tokens), so it never goes into the
-- repo or a chat: straight from one SQL editor into the other.

with
sc as (
  select count(*) n,
    coalesce(string_agg(format('(%s,%L,%s,%s,%s,%L,%L)', id, name, score, correct, len, mode, created_at),
      E',\n' order by id), '') v,
    md5(coalesce(string_agg(format('%L|%L|%L|%L|%L|%L|%L', id, name, score, correct, len, mode, created_at),
      E'\n' order by id), '')) h
  from public.scores),
pl as (
  select count(*) n,
    coalesce(string_agg(format('(%L,%L,%L,%L,%L)', token, name, collected, fp, updated_at),
      E',\n' order by token), '') v,
    md5(coalesce(string_agg(format('%L|%L|%L|%L|%L', token, name, collected, fp, updated_at),
      E'\n' order by token), '')) h
  from public.players),
fb as (
  select count(*) n,
    coalesce(string_agg(format('(%s,%L,%L,%L,%L,%L,%L)', id, qid, claim, name, token, lang, created_at),
      E',\n' order by id), '') v,
    md5(coalesce(string_agg(format('%L|%L|%L|%L|%L|%L|%L', id, qid, claim, name, token, lang, created_at),
      E'\n' order by id), '')) h
  from public.feedback),
bo as (
  select count(*) n,
    coalesce(string_agg(format('(%s,%L,%s,%L,%L)', id, name, points, reason, created_at),
      E',\n' order by id), '') v,
    md5(coalesce(string_agg(format('%L|%L|%L|%L|%L', id, name, points, reason, created_at),
      E'\n' order by id), '')) h
  from public.bonus)
select
$IMPORT$-- Nöggi-Kahoot → dm-quiz project: step 2 of 2, the IMPORT
-- Generated by docs/move-to-dm-quiz-export.sql in the old project. Run it in the
-- dm-quiz project's SQL editor. Safe to run again (existing rows are kept).
-- It creates only nk_* objects and never touches the dm_* tables or their rules.

-- ------------------------------------------------------------------ tables
create table if not exists public.nk_scores (
  id bigint generated always as identity primary key,
  name text not null check (char_length(name) between 1 and 14),
  score int not null check (score between 0 and 40000),
  correct int not null check (correct between 0 and 23),
  len int not null check (len in (10,23)),
  mode text not null check (mode in ('23','10','⚡10','👾10')),
  created_at timestamptz not null default now()
);
create table if not exists public.nk_players (
  token uuid primary key,
  name text not null check (char_length(name) between 1 and 14),
  collected jsonb not null default '[]',
  fp text,
  updated_at timestamptz not null default now()
);
create index if not exists nk_players_fp_idx on public.nk_players (fp);
create table if not exists public.nk_feedback (
  id bigint generated always as identity primary key,
  qid text not null check (char_length(qid) between 1 and 40),
  claim text not null check (char_length(claim) between 1 and 200),
  name text check (char_length(name) between 1 and 14),
  token uuid,
  lang text check (lang in ('de','fr','en')),
  created_at timestamptz not null default now()
);
create table if not exists public.nk_bonus (
  id bigint generated always as identity primary key,
  name text not null check (char_length(name) between 1 and 14),
  points int not null check (points between -40000 and 40000),
  reason text,
  created_at timestamptz not null default now()
);

-- ------------------------------------------ access: the same as in the old project
-- scores: anon inserts and reads (the leaderboard). players: no direct access,
-- only through the functions below. feedback: anon inserts only. bonus: anon reads.
alter table public.nk_scores   enable row level security;
alter table public.nk_players  enable row level security;
alter table public.nk_feedback enable row level security;
alter table public.nk_bonus    enable row level security;
drop policy if exists "anon insert" on public.nk_scores;
drop policy if exists "anon read"   on public.nk_scores;
drop policy if exists "anon insert" on public.nk_feedback;
drop policy if exists "anon read"   on public.nk_bonus;
create policy "anon insert" on public.nk_scores   for insert to anon with check (true);
create policy "anon read"   on public.nk_scores   for select to anon using (true);
create policy "anon insert" on public.nk_feedback for insert to anon with check (true);
create policy "anon read"   on public.nk_bonus    for select to anon using (true);

create or replace function public.nk_player_get(tok uuid)
returns table(name text, collected jsonb)
language sql security definer set search_path = public as
$$ select name, collected from nk_players where token = tok $$;

create or replace function public.nk_player_upsert(tok uuid, pname text, pcollected jsonb, pfp text)
returns void language sql security definer set search_path = public as
$$ insert into nk_players(token, name, collected, fp) values (tok, pname, pcollected, pfp)
   on conflict (token) do update set name = excluded.name,
     collected = excluded.collected, fp = excluded.fp, updated_at = now() $$;

create or replace function public.nk_player_by_fp(pfp text)
returns table(token uuid, name text, collected jsonb)
language sql security definer set search_path = public as
$$ select token, name, collected from nk_players
   where fp = pfp and length(coalesce(pfp,'')) > 8
     and (select count(*) from nk_players p2 where p2.fp = pfp) = 1 $$;

create or replace function public.nk_player_by_name(pname text)
returns table(token uuid, name text, collected jsonb)
language sql security definer set search_path = public as
$$ select token, name, collected from nk_players
   where lower(name) = lower(pname)
     and (select count(*) from nk_players p2 where lower(p2.name) = lower(pname)) = 1 $$;

create or replace function public.nk_feedback_list()
returns table(created_at timestamptz, qid text, claim text, name text, lang text)
language sql security definer set search_path = public as
$$ select f.created_at, f.qid, f.claim, f.name, f.lang
   from nk_feedback f order by f.created_at desc limit 200 $$;

grant execute on function public.nk_player_get(uuid) to anon;
grant execute on function public.nk_player_upsert(uuid, text, jsonb, text) to anon;
grant execute on function public.nk_player_by_fp(text) to anon;
grant execute on function public.nk_player_by_name(text) to anon;
grant execute on function public.nk_feedback_list() to anon;

-- -------------------------------------------------------------------- data
$IMPORT$
|| case when sc.n = 0 then '' else
   'insert into public.nk_scores (id, name, score, correct, len, mode, created_at) overriding system value values'
   || E'\n' || sc.v || E'\non conflict (id) do nothing;\n' end
|| case when pl.n = 0 then '' else
   'insert into public.nk_players (token, name, collected, fp, updated_at) values'
   || E'\n' || pl.v || E'\non conflict (token) do nothing;\n' end
|| case when fb.n = 0 then '' else
   'insert into public.nk_feedback (id, qid, claim, name, token, lang, created_at) overriding system value values'
   || E'\n' || fb.v || E'\non conflict (id) do nothing;\n' end
|| case when bo.n = 0 then '' else
   'insert into public.nk_bonus (id, name, points, reason, created_at) overriding system value values'
   || E'\n' || bo.v || E'\non conflict (id) do nothing;\n' end
|| $IMPORT$
-- new rows continue after the copied ids
select setval(pg_get_serial_sequence('public.nk_scores', 'id'),   coalesce((select max(id) from public.nk_scores), 0) + 1, false);
select setval(pg_get_serial_sequence('public.nk_feedback', 'id'), coalesce((select max(id) from public.nk_feedback), 0) + 1, false);
select setval(pg_get_serial_sequence('public.nk_bonus', 'id'),    coalesce((select max(id) from public.nk_bonus), 0) + 1, false);

notify pgrst, 'reload schema';

-- ------------------------------------------------------------------ checks
create temp table if not exists _nk_check (n int, check_name text, ok boolean, detail text);
truncate _nk_check;
create temp table if not exists _nk_expected (t text, n bigint, h text);
truncate _nk_expected;
insert into _nk_expected values
$IMPORT$
|| format('  (%L, %s, %L), (%L, %s, %L), (%L, %s, %L), (%L, %s, %L);',
     'nk_scores', sc.n, sc.h, 'nk_players', pl.n, pl.h, 'nk_feedback', fb.n, fb.h, 'nk_bonus', bo.n, bo.h)
|| $IMPORT$

do $$
declare e record; got bigint; h text; v int; w int; x int; y int; i int := 0;
begin
  for e in select * from _nk_expected order by t loop
    i := i + 1;
    execute format('select count(*) from public.%I', e.t) into got;
    if e.t = 'nk_scores' then
      select md5(coalesce(string_agg(format('%L|%L|%L|%L|%L|%L|%L', id, name, score, correct, len, mode, created_at), E'\n' order by id), '')) into h from public.nk_scores;
    elsif e.t = 'nk_players' then
      select md5(coalesce(string_agg(format('%L|%L|%L|%L|%L', token, name, collected, fp, updated_at), E'\n' order by token), '')) into h from public.nk_players;
    elsif e.t = 'nk_feedback' then
      select md5(coalesce(string_agg(format('%L|%L|%L|%L|%L|%L|%L', id, qid, claim, name, token, lang, created_at), E'\n' order by id), '')) into h from public.nk_feedback;
    else
      select md5(coalesce(string_agg(format('%L|%L|%L|%L|%L', id, name, points, reason, created_at), E'\n' order by id), '')) into h from public.nk_bonus;
    end if;
    insert into _nk_check values (i, e.t || ': all rows copied', got = e.n and h = e.h,
      got || ' of ' || e.n || ' rows' || case when h = e.h then ', checksum matches' else ', CHECKSUM DIFFERS' end);
  end loop;

  -- the wedding quiz, as its guests (anon), sees exactly what it saw before
  perform set_config('request.jwt.claims', '{"role":"anon"}', true);
  set local role anon;
  select count(*) into v from public.nk_scores;
  select count(*) into w from public.nk_players;
  select count(*) into x from public.nk_bonus;
  select count(*) into y from public.nk_feedback_list();
  reset role;
  insert into _nk_check values
    (5, 'Guests read the leaderboard and bonus', v = (select count(*) from public.nk_scores) and x = (select count(*) from public.nk_bonus),
        v || ' scores, ' || x || ' bonus rows'),
    (6, 'Guests cannot list players (only via the functions)', w = 0, w || ' rows visible'),
    (7, 'Report list works', y = least((select count(*) from public.nk_feedback), 200), y || ' reports');

  -- DM stays as migration 005 left it
  set local role anon;
  select count(*) into v from public.dm_players;
  select count(*) into w from public.dm_stars;
  reset role;
  insert into _nk_check values (8, 'DM names still hidden from anon', v = 0 and w = 0, v || ' players, ' || w || ' stars visible');
  perform set_config('request.jwt.claims', '', true);
end $$;

select case when ok then '✅' else '❌' end as " ", check_name, detail
  from _nk_check order by n;
$IMPORT$ as import_script
from sc, pl, fb, bo;
